// <auto-generated />
namespace CourseWork.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Deletetutorrequest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Deletetutorrequest));
        
        string IMigrationMetadata.Id
        {
            get { return "201511071845369_Delete tutor request"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
